# 前端异步编程规范

## 1. 手写Promise

### 1.1 resolve 和 reject

```javascript
let p1 = new Promise((resolve, reject) => {
    resolve('success')
    reject('fail')
})
console.log('p1', p1)

let p2 = new Promise((resolve, reject) => {
    reject('success')
    resolve('fail')
})
console.log('p2', p2)

let p3 = new Promise((resolve, reject) => {
    throw('error')
})
console.log('p3', p3)
```

![download_image](https://gitee.com/dx-smallpig/typora-image/raw/master/images/download_image.png)

这里说明了Promise的四个特点：

1. 执行了resolve，Promise状态会变成fulfilled；
2. 执行了reject，Promise状态会变成rejected；
3. Promise状态不可逆，第一次成功就永久为fulfilled，第一次失败就永远状态为rejected；
4. Promise中有throw的话，就相当于执行了reject；

#### 1.1.1 实现 resolve 和 reject

1. Promise的初始状态是pending；
2. 需要对resolve和reject绑定this：**确保resolve和reject的this指向永远指向当前的MyPromise实例，防止随着函数 执行环境的改变而改变**；

```javascript
class MyPromise {
    // 构造方法
    constructor(executor){
        // 初始化值
        this.initValue()
        // 初始化this指向 
        this.initBind()
        // 执行传进来的函数
        executor(this.resolve, this.reject)
    }
    
    initValue() {
        // 初始化值
        this.PromiseResult = null // 结果
        this.PromiseState = 'pending' // 状态
    }
    
    initBind() {
        // 初始化this，这里的this都是实例对象
        // 实例初始自身没有 resolve 和 reject 方法，只能从原型链上获取
        // 原型链上的方法 this 的指向是 underfind，需要将this指向实例，并将方法赋值给实例对象
        this.resolve = this.resolve.bind(this)
        this.reject = this.reject.bind(this)
    }
    
    resolve(value) {
        // 如果执行resolve，状态变为fulfilled
        this.PromiseState = 'fulfilled'
        // 结果为传进来的值
        this.PromiseResult = value
    }

    reject(reason) {
        // 如果执行reject，状态变为rejected
        this.PromiseState = 'rejected'
        // 结果为传进来的reason
        this.PromiseResult = reason
    }
}
```

```javascript
const test1 = new MyPromise((resolve, reject) => {
    resolve('success')
})
console.log(test1) // MyPromise { PromiseState: 'fulfilled', PromiseResult: 'success' }

const test2 = new MyPromise((resolve, reject) => {
    reject('fail')
})
console.log(test2) // MyPromise { PromiseState: 'rejected', PromiseResult: 'fail' }
```



#### 1.1.2 状态不可变

```javascript
const test1 = new MyPromise((resolve, reject) => {
    resolve('success')
    reject('fail')
})
console.log(test1) // MyPromise { PromiseState: 'rejected', PromiseResult: 'fail' }
```

正确确的应该是状态为fulfilled，但这里状态又变成了rejected。

Promise有三种状态：

- pending：等待中，是初始状态；
- fulfilled：成功状态；
- rejected：失败状态；

一旦状态从pending变为fulfilled或者rejected，那么此Promise实例的状态就不可以改变了。

![image-20240530170118967](https://gitee.com/dx-smallpig/typora-image/raw/master/images/image-20240530170118967.png)

```javascript
class MyPromise {
    // 构造方法
    constructor(executor){
        // 初始化值
        this.initValue()
        // 初始化this指向 
        this.initBind()
        // 执行传进来的函数
        executor(this.resolve, this.reject)
    }
    
    initValue() {
        // 初始化值
        this.PromiseResult = null // 结果
        this.PromiseState = 'pending' // 状态
    }
    
    initBind() {
        // 初始化this，这里的this都是实例对象
        // 实例初始自身没有 resolve 和 reject 方法，只能从原型链上获取
        // 原型链上的方法 this 的指向是 underfind，需要将this指向实例，并将方法赋值给实例对象
        this.resolve = this.resolve.bind(this)
        this.reject = this.reject.bind(this)
    }
    
    resolve(value) {
+       // state是不可变的
+       if (this.PromiseState !== 'pending') return
        // 如果执行resolve，状态变为fulfilled
        this.PromiseState = 'fulfilled'
        // 结果为传进来的值
        this.PromiseResult = value
    }

    reject(reason) {
+       // state是不可变的
+       if (this.PromiseState !== 'pending') return
        // 如果执行reject，状态变为rejected
        this.PromiseState = 'rejected'
        // 结果为传进来的reason
        this.PromiseResult = reason
    }
}
```

```javascript
const test1 = new MyPromise((resolve, reject) => {
    // 只以第一次为准
    resolve('success')
    reject('fail')
})
console.log(test1) // MyPromise { PromiseState: 'fulfilled', PromiseResult: 'success' }
```



#### 1.1.3 throw

![image-20240530170921501](https://gitee.com/dx-smallpig/typora-image/raw/master/images/image-20240530170921501.png)

Promise中有throw的话，就相当于执行了reject。这就要使用try catch了

```javascript
class MyPromise {
    // 构造方法
    constructor(executor){
        // 初始化值
        this.initValue()
        // 初始化this指向 
        this.initBind()
+       try {
            // 执行传进来的函数
            executor(this.resolve, this.reject)
+       } catch(e) {
+           // 捕捉到错误直接执行reject
+           this.reject(e)
+       }
    }
    
    initValue() {
        // 初始化值
        this.PromiseResult = null // 结果
        this.PromiseState = 'pending' // 状态
    }
    
    initBind() {
        // 初始化this，这里的this都是实例对象
        // 实例初始自身没有 resolve 和 reject 方法，只能从原型链上获取
        // 原型链上的方法 this 的指向是 underfind，需要将this指向实例，并将方法赋值给实例对象
        this.resolve = this.resolve.bind(this)
        this.reject = this.reject.bind(this)
    }
    
    resolve(value) {
        // state是不可变的
        if (this.PromiseState !== 'pending') return
        // 如果执行resolve，状态变为fulfilled
        this.PromiseState = 'fulfilled'
        // 结果为传进来的值
        this.PromiseResult = value
    }

    reject(reason) {
        // state是不可变的
        if (this.PromiseState !== 'pending') return
        // 如果执行reject，状态变为rejected
        this.PromiseState = 'rejected'
        // 结果为传进来的reason
        this.PromiseResult = reason
    }
}
```



### 1.2 then

平时业务中then的使用一般如下：

```javascript
// 马上输出 ”success“
const p1 = new Promise((resolve, reject) => {
    resolve('success')
}).then(res => console.log(res), err => console.log(err))

// 1秒后输出 ”fail“
const p2 = new Promise((resolve, reject) => {
    setTimeout(() => {
        reject('fail')
    }, 1000)
}).then(res => console.log(res), err => console.log(err))

// 链式调用 输出 200
const p3 = new Promise((resolve, reject) => {
    resolve(100)
}).then(res => 2 * res, err => console.log(err))
  .then(res => console.log(res), err => console.log(err))
```

根据上述代码可以确定：

1. then接收两个回调，一个是成功回调，一个是失败回调；
2. 当Promise状态为fulfilled执行成功回调，为rejected执行失败回调；
3. 如resolve或reject在定时器里，则定时器结束后再执行then；
4. then支持链式调用，下一次then执行受上一次then返回值的影响；

#### 1.2.1 实现then

```javascript
    then(onFulfilled, onRejected) {
        // 接收两个回调 onFulfilled, onRejected
        
        // 参数校验，确保一定是函数
        onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val
        onRejected = typeof onRejected === 'function' ? onRejected : reason => { throw reason }

        if (this.PromiseState === 'fulfilled') {
            // 如果当前为成功状态，执行第一个回调
            onFulfilled(this.PromiseResult)
        } else if (this.PromiseState === 'rejected') {
            // 如果当前为失败状态，执行第二哥回调
            onRejected(this.PromiseResult)
        }

    }
```



#### 1.2.2 定时器

```javascript
// 1秒后输出 ”fail“
const p2 = new Promise((resolve, reject) => {
    setTimeout(() => {
        reject('fail')
    }, 1000)
}).then(res => console.log(res), err => console.log(err))
```

![image-20240530172409287](https://gitee.com/dx-smallpig/typora-image/raw/master/images/image-20240530172409287.png)

我们不能确保1秒后才执行then函数，但是我们可以保证1秒后再执行then里的回调

在这1秒时间内，我们可以先把then里的两个回调保存起来，然后等到1秒过后，执行了resolve或者reject，咱们再去判断状态，并且判断要去执行刚刚保存的两个回调中的哪一个回调。

那么问题来了，我们怎么知道当前1秒还没走完甚至还没开始走呢？其实很好判断，只要状态是pending，那就证明定时器还没跑完，因为如果定时器跑完的话，那状态肯定就不是pending，而是fulfilled或者rejected

那是用什么来保存这些回调呢？建议使用数组，因为一个promise实例可能会多次then，用数组就一个一个保存了

```javascript
    initValue() {
        // 初始化值
        this.PromiseResult = null // 终值
        this.PromiseState = 'pending' // 状态
+       this.onFulfilledCallbacks = [] // 保存成功回调
+       this.onRejectedCallbacks = [] // 保存失败回调
    }

    resolve(value) {
        // state是不可变的
        if (this.PromiseState !== 'pending') return
        // 如果执行resolve，状态变为fulfilled
        this.PromiseState = 'fulfilled'
        // 终值为传进来的值
        this.PromiseResult = value
        // 执行保存的成功回调
+       while (this.onFulfilledCallbacks.length) {
+           this.onFulfilledCallbacks.shift()(this.PromiseResult)
+       }
    }

    reject(reason) {
        // state是不可变的
        if (this.PromiseState !== 'pending') return
        // 如果执行reject，状态变为rejected
        this.PromiseState = 'rejected'
        // 终值为传进来的reason
        this.PromiseResult = reason
        // 执行保存的失败回调
+       while (this.onRejectedCallbacks.length) {
+           this.onRejectedCallbacks.shift()(this.PromiseResult)
+       }
    }
    
    then(onFulfilled, onRejected) {
        // 接收两个回调 onFulfilled, onRejected

        // 参数校验，确保一定是函数
        onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val
        onRejected = typeof onRejected === 'function' ? onRejected : reason => { throw reason }

        if (this.PromiseState === 'fulfilled') {
            // 如果当前为成功状态，执行第一个回调
            onFulfilled(this.PromiseResult)
        } else if (this.PromiseState === 'rejected') {
            // 如果当前为失败状态，执行第二哥回调
            onRejected(this.PromiseResult)
+       } else if (this.PromiseState === 'pending') {
+           // 如果状态为待定状态，暂时保存两个回调
+           this.onFulfilledCallbacks.push(onFulfilled)
+           this.onRejectedCallbacks.push(onRejected)
+       }

    }

```



#### 1.2.3 链式调用

then支持链式调用，下一次then执行受上一次then返回值的影响，给大家举个例子：

```javascript
// 链式调用 输出 200
const p3 = new Promise((resolve, reject) => {
  resolve(100)
}).then(res => 2 * res, err => console.log(err))
  .then(res => console.log(res), err => console.log(err))

// 链式调用 输出300
const p4 = new Promise((resolve, reject) => {
  resolve(100)
}).then(res => new Promise((resolve, reject) => resolve(3 * res)), err => console.log(err))
  .then(res => console.log(res), err => console.log(err))
```

根据上文，可以得到：

1. then方法本身会返回一个新的Promise对象；
2. 如果返回值是promise对象，返回值为成功，新promise就是成功；
3. 如果返回值是promise对象，返回值为失败，新promise就是失败；
4. 如果返回值非promise对象，新promise对象就是成功，值为此返回值；

then是Promise上的方法，那如何实现then完还能再then呢？

then执行后返回一个Promise对象就行了，就能保证then完还能继续执行then；

![image-20240530172927635](https://gitee.com/dx-smallpig/typora-image/raw/master/images/image-20240530172927635.png)

```javascript
then(onFulfilled, onRejected) {
		// then的两个参数 如果是函数，执行函数，不是函数，转成函数执行
		onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val;
		onRejected =
			typeof onRejected === 'function'
				? onRejected
				: reason => {
						throw reason;
				  };

		// 为了确保then返回的结果是一个promise对象
		var thenPromise = new MyPromise((resolve, reject) => {
			// 针对 resolve reject 的处理结果做收敛
			const handlePromise = cb => {
				// cb 可以是 onFulfilled onRejected
                try {
                    const result = cb(this.PromiseResult);

                    if (result === thenPromise) {
                        throw new Error('not self');
                    }

                    if (result instanceof MyPromise) {
                        result.then(resolve, reject);
                    } else {
                        resolve(result);
                    }
                } catch (err) {
                    reject(err);
                    throw new Error(err);
                }
			};

			// 处理状态变化
			if (this.PromiseStatus === 'fulfilled') {
				handlePromise(onFulfilled);
			} else if (this.PromiseStatus === 'rejected') {
				handlePromise(onRejected);
			} else {
				// 针对pending状态，此处添加回调
                // bind 用于返回一个函数保存进队列，不加bind就直接执行了
				this.onFulfilledCallbacks.push(handlePromise.bind(this, onFulfilled));
				this.onRejectedCallbacks.push(handlePromise.bind(this, onRejected));
			}
		});

		return thenPromise;
	}
```



#### 1.2.4 执行顺序

```javascript
const p = new Promise((resolve, reject) => {
    resolve(1)
}).then(res => console.log(res), err => console.log(err))

console.log(2)

// 输出顺序是 2 1
```

then方法是微任务

这里为了实现类似的功能，使用setTimeout代替（setTimeout为宏任务，此处主要跟在全局上的console对比）

```javascript
then(onFulfilled, onRejected) {
		// then的两个参数 如果是函数，执行函数，不是函数，转成函数执行
		onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val;
		onRejected =
			typeof onRejected === 'function'
				? onRejected
				: reason => {
						throw reason;
				  };

		// 为了确保then返回的结果是一个promise对象
		var thenPromise = new MyPromise((resolve, reject) => {
			// 针对 resolve reject 的处理结果做收敛
			const handlePromise = cb => {
				// cb 可以是 onFulfilled onRejected
				setTimeout(() => {
					try {
						const result = cb(this.PromiseResult);

						if (result === thenPromise) {
							throw new Error('not self');
						}

						if (result instanceof MyPromise) {
							result.then(resolve, reject);
						} else {
							resolve(result);
						}
					} catch (err) {
						reject(err);
						throw new Error(err);
					}
				});
			};

			// 处理状态变化
			if (this.PromiseStatus === 'fulfilled') {
				handlePromise(onFulfilled);
			} else if (this.PromiseStatus === 'rejected') {
				handlePromise(onRejected);
			} else {
				// 针对pending状态，此处添加回调
				this.onFulfilledCallbacks.push(handlePromise.bind(this, onFulfilled));
				this.onRejectedCallbacks.push(handlePromise.bind(this, onRejected));
			}
		});

		return thenPromise;
	}
```



#### 1.2.5 完整代码

```javascript
class MyPromise {
	constructor(executor) {
		// 初始化赋值
		this.initValue();
		this.initBind();
		try {
			executor(this.resolve, this.reject);
		} catch (e) {
			this.reject(e);
		}
	}

	initValue() {
		this.PromiseStatus = 'pending';
		this.PromiseResult = null;
		// 要把当前执行的事件（包含异步事件）存储下来
		this.onFulfilledCallbacks = []; // 存储成功的cb
		this.onRejectedCallbacks = []; // 存储失败的cb
	}

	initBind() {
		// 通过构造函数创建出的实例，test1调用resolve，此时的resolve函数是MyPromise上的resolve，但是this不指向test1，bind(this)
		this.resolve = this.resolve.bind(this);
		this.reject = this.reject.bind(this);
	}

	resolve(value) {
		if (this.PromiseStatus !== 'pending') {
			return;
		}

		this.PromiseStatus = 'fulfilled';
		this.PromiseResult = value;

		// 执行 onFulfilledCallbacks
		while (this.onFulfilledCallbacks.length) {
			this.onFulfilledCallbacks.shift()(this.PromiseResult);
		}

		// 1. 全量按序执行 onFulfilledCallbacks -> onFulfilled(this.PromiseResult) .then().then()
		// 2. shift() then()
	}

	reject(reason) {
		if (this.PromiseStatus !== 'pending') {
			return;
		}

		this.PromiseStatus = 'rejected';
		this.PromiseResult = reason;

		// 执行onRejectedCallbacks
		while (this.onRejectedCallbacks.length) {
			this.onRejectedCallbacks.shift()(this.PromiseResult);
		}
	}

	then(onFulfilled, onRejected) {
		// then的两个参数 如果是函数，执行函数，不是函数，转成函数执行
		onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val;
		onRejected =
			typeof onRejected === 'function'
				? onRejected
				: reason => {
						throw reason;
				  };

		// 为了确保then返回的结果是一个promise对象
		var thenPromise = new MyPromise((resolve, reject) => {
			// 针对 resolve reject 的处理结果做收敛
			const handlePromise = cb => {
				// cb 可以是 onFulfilled onRejected
				setTimeout(() => {
					try {
						const result = cb(this.PromiseResult);

						if (result === thenPromise) {
							throw new Error('not self');
						}

						if (result instanceof MyPromise) {
							result.then(resolve, reject);
						} else {
							resolve(result);
						}
					} catch (err) {
						reject(err);
						throw new Error(err);
					}
				});
			};

			// 处理状态变化
			if (this.PromiseStatus === 'fulfilled') {
				handlePromise(onFulfilled);
			} else if (this.PromiseStatus === 'rejected') {
				handlePromise(onRejected);
			} else {
				// 针对pending状态，此处添加回调
				this.onFulfilledCallbacks.push(handlePromise.bind(this, onFulfilled));
				this.onRejectedCallbacks.push(handlePromise.bind(this, onRejected));
			}
		});

		return thenPromise;
	}
}

```



### 1.3 其他方法

#### 1.3.1 all

1. 接收一个Promise数组，数组中如有非Promise项，则此项当做成功；
2. 如果所有Promise都成功，则返回成功结果数组；
3. 如果有一个Promise失败，则返回这个失败结果；

```javascript
static all(promises) {
    const result = []
    let count = 0
    return new MyPromise((resolve, reject) => {
        const addData = (index, value) => {
            result[index] = value
            count++
            if (count === promises.length) resolve(result)
        }
        promises.forEach((promise, index) => {
            if (promise instanceof MyPromise) {
                promise.then(res => {
                    addData(index, res)
                }, err => reject(err))
            } else {
                addData(index, promise)
            }
        })
    })
}
```



#### 1.3.2 race

1. 接收一个Promise数组，数组中如有非Promise项，则此项当做成功；
2. 哪个Promise最快得到结果，就返回那个结果，无论成功失败；

```javascript
static race(promises) {
    return new MyPromise((resolve, reject) => {
        promises.forEach(promise => {
            if (promise instanceof MyPromise) {
                promise.then(res => {
                    resolve(res)
                }, err => {
                    reject(err)
                })
            } else {
                resolve(promise)
            }
        })
    })
}
```



#### 1.3.3 allSettled

1. 接收一个Promise数组，数组中如有非Promise项，则此项当做成功；
2. 把每一个Promise的结果，集合成数组后返回；

```javascript
static allSettled(promises) {
    return new Promise((resolve, reject) => {
        const res = []
        let count = 0
        const addData = (status, value, i) => {
            res[i] = {
                status,
                value
            }
            count++
            if (count === promises.length) {
                resolve(res)
            }
        }
        promises.forEach((promise, i) => {
            if (promise instanceof MyPromise) {
                promise.then(res => {
                    addData('fulfilled', res, i)
                }, err => {
                    addData('rejected', err, i)
                })
            } else {
                addData('fulfilled', promise, i)
            }
        })
    })
}
```



#### 1.3.4 any

与all相反

1. 接收一个Promise数组，数组中如有非Promise项，则此项当做成功；
2. 如果有一个Promise成功，则返回这个成功结果；
3. 如果所有Promise都失败，则报错；

```javascript
static any(promises) {
    return new Promise((resolve, reject) => {
        let count = 0
        promises.forEach((promise) => {
            promise.then(val => {
                resolve(val)
            }, err => {
                count++
                if (count === promises.length) {
                    reject(new Error('All promises were rejected'))
                }
            })
        })
    })
}
}
```



## 2. 字节面试题

```javascript
class Scheduler {
  add(promiseCreator) { ... }
  // ...
}

const timeout = (time) => new Promise(resolve => {
  setTimeout(resolve, time)
})

const scheduler = new Scheduler(n)
const addTask = (time, order) => {
  scheduler.add(() => timeout(time)).then(() => console.log(order))
}

addTask(1000, '1')
addTask(500, '2')
addTask(300, '3')
addTask(400, '4')

// n = 2,打印顺序是：2 3 1 4
```

流程分析：

整个的完整执行流程：

1. 起始1、2两个任务开始执行；
2. 500ms时，2任务执行完毕，输出2，任务3开始执行；
3. 800ms时，3任务执行完毕，输出3，任务4开始执行；
4. 1000ms时，1任务执行完毕，输出1，此时只剩下4任务在执行；
5. 1200ms时，4任务执行完毕，输出4；

当资源不足时将任务加入等待队列，当资源足够时，将等待队列中的任务取出执行

在调度器中一般会有一个等待队列queue，存放当资源不够时等待执行的任务 具有并发数据限制，假设通过max设置允许同时运行的任务，还需要count表示当前正在执行的任务数量 当需要执行一个任务A时，先判断count==max 如果相等说明任务A不能执行，应该被阻塞，阻塞的任务放进queue中，等待任务调度器管理 如果count<max说明正在执行的任务数没有达到最大容量，那么count++执行任务A,执行完毕后count-- 此时如果queue中有值，说明之前有任务因为并发数量限制而被阻塞，现在count<max，任务调度器会将对头的任务弹出执行

```javascript
class Scheduler {
  constructor(max) {
    this.max = max;
    this.count = 0; // 用来记录当前正在执行的异步函数
    this.queue = new Array(); // 表示等待队列
  }
  async add(promiseCreator) {
    /*
        此时count已经满了，不能执行本次add需要阻塞在这里，将resolve放入队列中等待唤醒,
        等到count<max时，从队列中取出执行resolve,执行，await执行完毕，本次add继续
        */
    if (this.count >= this.max) {
      await new Promise((resolve, reject) => this.queue.push(resolve));
    }

    this.count++;
    let res = await promiseCreator();
    this.count--;
    if (this.queue.length) {
      // 依次唤醒add
      // 若队列中有值，将其resolve弹出，并执行
      // 以便阻塞的任务，可以正常执行
      this.queue.shift()();
    }
    return res;
  }
}

const timeout = time =>
  new Promise(resolve => {
    setTimeout(resolve, time);
  });

const scheduler = new Scheduler(2);

const addTask = (time, order) => {
  //add返回一个promise，参数也是一个promise
  scheduler.add(() => timeout(time)).then(() => console.log(order));
};
  
  addTask(1000, '1');
  addTask(500, '2');
  addTask(300, '3');
  addTask(400, '4');
  
// output: 2 3 1 4
```

































